### ISSUE TITLE
CentOS-8 

### ISSUE THREAD

**Issue by damacus** [sous-chefs/syslog_ng#34]
### :speaking_head: Foreword

Thank for taking the time to fill this bug report fully. Without it we may not be able to fix the bug, and the issue may be closed without resolution.

## :ghost: Brief Description

`libmongoc` is required but unavailable:

```bash
Problem: package syslog-ng-mongodb-3.23.1-1.el8.x86_64 requires libmongoc-1.0.so.0()(64bit), but none of the providers can be installed
```

## :pancakes: Cookbook version

Latest

## :woman_cook:  Chef-Infra Version

16
## :tophat: Platform details

CentOS-8

## :police_car: Expected behavior

It should pass the kitchen tests

## :heavy_plus_sign: Additional context

Add any other context about the problem here. e.g. related issues or existing pull requests.

**Comment by bmhughes** [comment]
This appears to be a bug in the upstream `centos:8` container as it happens on a clean kitchen container but passes on vagrant (and passed with dokken last week).

**Comment by damacus** [comment]
Might be worth dropping an issue in [Dokken Images](https://github.com/test-kitchen/dokken-images)

**Comment by bmhughes** [comment]
Yeh I was planning on it once i've had time to 100% confirm, haven't had time to circle back to it yet.

**Comment by bmhughes** [comment]
https://github.com/test-kitchen/dokken-images/issues/31

It works with a locally build container, upstream bug report created.
